### ISSUE TITLE
cannot compile xcodeProject

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/OFXcodeMenu#39] opened 2015-09-20 20:54 UTC
after update to Xcode 7.0, OF menu disappear as I expect.
so I re-download xodeproject file from this github page.

but I CANNOT build it. instead
"
error : Unable to create directory / Users/{myUserName}/Library/Application Support/Developer/Shared/Xocde/Plugins/OFXcodeMenu.xcplugin/Contents (Permission denied)
"

so I tried with  Alcatraz Xcode package manager. but that's not work neither.
press the 'install button', change to 'installing' and graph is growing, but soon back to 'install'

**Comment by kylemcdonald** [comment] 2015-09-21 23:01
i just updated Xcode and could not reproduce this.

**Comment by admsyn** [comment] 2015-09-22 02:55
Is the error a literal copy-paste? There's a space after the "/" in `/ Users/`.

When you say you downloaded the xcodeproject file, do you mean you cloned the whole repository or just downloaded the .xcodeproj? If you just got the .xcodeproj can you try cloning the whole repository, or downloading the full source from https://github.com/openframeworks/OFXcodeMenu/releases ?

I can't reproduce this either fwiw. It may help to remove the old plugin and re-build, if for some reason the original one was created under a different user account.

**Comment by icq4ever** [comment] 2015-09-22 09:43
sorry. its 

/Users/~
I'm not cloned. just download zip file. 

I tired again with Xcode 7.0 zip the address you give me (https://github.com/openframeworks/OFXcodeMenu/releases) but still cannot build.

after that... I cloned whole repository with GitHub app for OS X. but still not working...
pretty weird..

![Uploading Screen Shot 2015-09-22 at 6.42.10 PM.png…]()

**Comment by admsyn** [comment] 2015-09-22 17:48
Can you try manually deleting the plugin from `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/` and re-building?

**Comment by icq4ever** [comment] 2015-10-03 10:02
manually delete the plugin directory is not working.
so I chanced "sharing & permissions" section, in "staff","everyone" from "Read only"to "Read & Write".
and I can build. 

before that, I check file permission on DiskUtility of OSX. but it's not work.
anyway. now OF Menu it works.

**Comment by admsyn** [comment] 2015-10-03 15:19
OK, thanks for the update @icq4ever. I don't think there's much that can be done from within OFXcodeMenu to fix that, so I'm going to close this.

**Closed by admsyn** 2015-10-03 15:19 UTC
